### ISSUE TITLE
Feature Wunsch: Zubehör nicht einzeln buchbar

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#101]
Wir haben einen Feature Wunsch. (Sollte das schon irgendwie gehen, würde ich mich über eine kurze Info freuen).

Wir hätten gerne, dass wir Zubehör zu Ressourcen definieren können, bspw. SDI-Kabel zu Kameras, dieses Zubehör aber nicht auch einzeln verleihbar ist, sondern wirklich nur zusammen mit der Ressource. 

Hintergrund: Wir wollen keine einzelnen Adapter oder Kabel verleihen müssen, sondern eben nur im Zusammenspiel mit Geräten.

**Comment by tiloman** [comment]
Es geht indem man die Zubehör Ressourcen für keine Gruppe verfügbar macht. Dann können sie als Zubehör den anderen Ressourcen zugeordnet werden und gebucht werden.
