### ISSUE TITLE
Admin / User: Gerät nicht buchbar obwohl verfügbar

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#102]
### Problem
Geräte können immer wieder für Zeiten nicht Gebucht werden in welchen diese allerdings verfügbar sind. Auch Verlängerungen der Geräte in diese Zeiten hinein ist leider nicht möglich. Auch nicht als Admin.

**Comment by mimosel** [comment]
Ich habe das gerade mal ausprobiert und der Fehler tritt bei mir nicht auf. Was muss man denn tun, um den zu reproduzieren?

**Comment by tiloman** [comment]
Das Problem ist behoben. Es trat nur in speziellen Situationen auf.
