### ISSUE TITLE
Admin/User: Gerät doppelt gebucht

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#103]
### Problem:
Bei uns wurde ein Gerät doppelt gebucht laut Inventarliste existiert dies allerdings nur einmal.
Wenn ich auf die Geräteeinstellungen zugreifen will bekomme ich die Error-Seite zu sehen.
Zuletzt: 19.04.2024 12:54 Uhr

**Comment by tiloman** [comment]
Es gab scheinbar ein Problem mit der Benennung, was zu einem rendering fehler geführt hat. Ich habe einen fix eingespielt (ca. 20min). Es betrifft nur die folgende Ressource: https://phka.simren.de/types/64

Hier sehe ich, dass es zwei Artikel gibt, einer davon ist deaktiviert.

**Comment by OneOfTwelve** [comment]
Ok. Ich nehme an das der Rendering Fehler dann auch zu der Doppelbuchung geführt hat?.

**Comment by tiloman** [comment]
sorry, ich hatte vergessen Bescheid zu geben. Der rendering fehler sollte nun behoben sein.

**Comment by OneOfTwelve** [comment]
Ja ist er. Konntest du herausfinden, wieso eine doppelte Buchung möglich war?

**Comment by tiloman** [comment]
Ich gehe davon aus, dass es denselben Grund hat. Ich habe mehrfach noch getestet und konnte keine Doppelbuchungen anlegen.
