### ISSUE TITLE
Admin: Unterstüzung von Markdown und Zeilenumbrüchen

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#104]
### Problem:
Wir haben längere Beschreibungen oder Erklärungen an einigen stellen in Simren und würden gerne noch viel mehr Informationen für die Nutzer zur Verfügung stellen, da allerdings die Zeilenumbrüche ignoriert werden sind insbesondere Auflistungen von Inhalten / Zubehör welches bei Geräten dabei ist absolut unübersichtlich ebenso wie technische Spezifikationen.

### Lösung:
1. eingegebene Zeilenumbrüche sollten nicht nur im Feld in welchem man sie eingibt angezeigt werden sondern auch dort wo die Informationen nur stur angezeigt werden.
2. eine Unterstützung von grundlegendem Markdown (fett, kursiv, Überschriften, Listen [geordnet und ungeordnet], links) einbauen

**Comment by ccupb** [comment]
+1

**Comment by tiloman** [comment]
<img width="1363" alt="image" src="https://github.com/user-attachments/assets/f9242cb7-6056-46f8-9e2e-93bd3eb2c22f">

Die Beschreibung kann nun formatiert werden.
