### ISSUE TITLE
(R-)Admin Verlängerungsanfrage nicht bearbeitbar

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#107]
### Problem:
Für die Buchung (#746) wurde eine Verlängerungsanfrage mit dem Kommentar "-" erstellt.
Möchte man nun die ANfrage bearbeiten ist irgendwas kaputt und man sieht den Text: "Content missing".

### Lösung:
Sonderzeichen nicht die Ausgabe kaputt machen lassen.

**Comment by tiloman** [comment]
Der Fehler hängt mit einer anderen Veränderung von gestern zusammen und nicht mit den Sonderzeichen. Fix ist auf dem Weg. Vermutlich in spätestens 20min gelöst.
