### ISSUE TITLE
Admin: Öffnungszeiten mit Unterbrechungen ermöglichen

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#109]
### Problem:
Bei uns betreuen Studierende die Ressourcenausgabe unsere Öffnungszeiten richten sich nach der Verfügbarkeit dieser.
Somit kommt es immer wieder vor, dass wir in unseren Öffnungszeiten Unterbrechungen haben. Diese lassen sich aktuell nicht mit den Öffnungszeiten in Simren abbilden, wodurch unsere Kunden nur in einem Bruchteil der Zeit Geräte Buchen können und zurückgeben.

### Lösung:
Einführen flexibler Öffnungszeiten so, dass mehrmals am Tag geöffnet sein kann und es mehrere geschlossene Zeiten geben kann. Wie dies zum Beispiel bei der Raumbuchung schon möglich ist.

**Comment by ccupb** [comment]
+1

**Comment by mimosel** [comment]
siehe dazu auch https://github.com/tiloman/simren-issues/issues/8

**Comment by OneOfTwelve** [comment]
@tiloman wir würden dieses Feature wirklich benötigen. Lässt sich irgendwie absehen wann mit der implementierung gerechnet werden kann?

**Comment by tiloman** [comment]
Ich kann das demnächst gerne angehen und hoffe es innerhalb des nächsten Monats umsetzen zu können.

**Comment by tiloman** [comment]
ist nun möglich @OneOfTwelve
