### ISSUE TITLE
(R-)Admin: Tagesübersicht im Dashboard übersichtlicher gestalten

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#11]
### Problem:
Die Tagesübersicht wird relativ schnell abgeschnitten und man sieht nicht mehr auf einen Blick ob und was zu tun ist über den Tag.

### Lösung:
- Uhrzeiten zu welchen nichts zu machen ist in der Liste ausblenden
- Die Liste immer auf die aktuelle Uhrzeit vorscrollen (evtl. sogar in Echtzeit), so dass man die nächsten paar Minuten/Stunden immer im Blick hat

**Comment by tiloman** [comment]
<img width="193" alt="image" src="https://user-images.githubusercontent.com/47814142/215309777-e4b858b9-629d-43df-bb1b-1f8fb7640be8.png">
Es wird einen toggle Button geben für die Ansicht: Detailansicht und Kompaktansicht. Bei der Kompaktansicht werden alle Zeitslots entfernt, die keine Buchungen beinhalten. Die Auswahl wird in einem Cookie gespeichert. 
Die Echtzeitansicht kann gerne in einem extra Issue festgehalten werden und könnte zu einem späteren Zeitpunkt realisiert werden.
