### ISSUE TITLE
Sortierung der Ressourcen im Buchungsprozess verbessern.

### ISSUE THREAD

**Issue by ccupb** [tiloman/simren-issues#114]
Im Buchungsprozess sollten die hinzufügbaren Ressourcen im Dropdown-Menü alphabetisch sortiert sein, oder noch besser die gleiche Oberfläche/Struktur erscheinen wie im Ressourcen-Tab (Nach Kategorien, mit Bildern, durchsuchbar).

**Comment by tiloman** [comment]
Ist nun alphabetisch sortiert und auch durchsuchbar. Die Anzeige mit Bildern wäre bei vielen Ressourcen zu umständlich meiner Meinung nach.
