### ISSUE TITLE
In Ressourcen-Infos immer zugehörige Artikel anzeigen, auch wenn nur ein Artikel existiert

### ISSUE THREAD

**Issue by ccupb** [tiloman/simren-issues#116]
In Ressourcen-Infos immer zugehörige Artikel anzeigen, auch wenn nur ein Artikel existiert. Zur Zeit wird nur folgender Text angezeigt: "Diese Ressource ist keine Ressourcengruppe. Wenn mehrere Artikel dieses Typs vorhanden sind, füge Artikel hinzu." Der einzige, etwas umständliche Weg, einzelne Artikel dieser Art zu editieren ist somit über die gesamte Inventar-Liste.

**Comment by tiloman** [comment]
Ist umgesetzt. Vielen Dank
