### ISSUE TITLE
Wechsel des Teamowners?

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#118]
Vielleicht bin ich nur blind, aber ich konnte nicht herausfinden, wie man den Teamowner wechseln kann? 
1. Geht das?
2. Steht das irgendwo in der Dokumentation?
3. Sollte der Teamowner (falls Wechsel nicht möglich) dann als best-practice nicht eher eine Funktionsadresse als eine Person sein?

**Comment by tiloman** [comment]
Ja, das geht aktuell nicht als Self-Service. 
Gerne einfach mir schreiben wer der owner werden soll.

**Comment by tiloman** [comment]
in der doku hinterlegt
