### ISSUE TITLE
Benutzer können nicht zu Ressourcenadministratoren gemacht werden

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#121]
Unter https://mzcrew.simren.de/users/8/edit kann man Benutzer editieren und sie im Feld "Ressourcenadministrator für ..." zu Ressourcenadministratoren machen. 

Problem: Wenn man den Dialog speichert, werden die Daten anscheinend nicht gespeichert. Bearbeitet man den Nutzer neu, ist das Feld "Ressourcenadministrator für" jedenfalls leer.

**Comment by tiloman** [comment]
ist gefixt
