### ISSUE TITLE
Benutzergruppen wer kann was im Support

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#122]
Unter "Benutergruppen – wer kann was" (fehlt ein "z"!), unter https://simren.de/support/benutergruppen-wer-kann-was/ werden leider keine Angaben dazu gemacht, inwiefern die Daten von Benutzern einsehbar sind. Das ist natürlich unschön, wenn man sich einen Überblick über das Thema Datenschutz machen will.

**Comment by tiloman** [comment]
Seite aktualisiert
