### ISSUE TITLE
Ressourcenadmin kann sein eigenes Profil nicht einsehen

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#123]
Ressourcenadmin kann sein eigenes Profil nicht einsehen
![Bild1](https://github.com/user-attachments/assets/a2ae9e80-35ec-4a6f-8134-78a822282fde)

Nach dem Klick folgt diese Fehlermeldung:
![Bild2](https://github.com/user-attachments/assets/962f2f47-ba1c-4d31-99bc-38fc88bb6693)

Die Fehlermeldung erscheint auch, wenn man händisch in die URL-Zeile https://mzcrew.simren.de/users/5/ (URL von einem anderen Profil) eingibt.

**Comment by tiloman** [comment]
Danke, der fix ist unterwegs. Heute abend sollte es wieder gehen.
