### ISSUE TITLE
Bug: "Buchung löschen" während eine Ressource ausgegeben ist führt zu Problemen.

### ISSUE THREAD

**Issue by ccupb** [tiloman/simren-issues#124]
Bug: "Buchung löschen" während eine Ressource ausgegeben ist führt dazu, dass man den Artikel gar nicht mehr ausleihen kann und man kann ihn auch nicht löschen.

**Comment by tiloman** [comment]
Buchungen, die ausgegeben sind können nun nicht mehr gelöscht werden. Bitte gib mir durch welche Artikel nun fälschlicherweise als ausgeliehen angezeigt werden. Gerne auch per Mail
