### ISSUE TITLE
Bug: Im Bereich "Benutzer|innen" werden maximal 10 Einträge pro Seite angezeigt, egal welche Einstellung (25, 50, 100) man auswählt.

### ISSUE THREAD

**Issue by ccupb** [tiloman/simren-issues#125]
Bug: Im Bereich "Benutzer|innen" werden maximal 10 Einträge pro Seite angezeigt, egal welche Einstellung (25, 50, 100) man auswählt.

**Comment by tiloman** [comment]
fixed
