### ISSUE TITLE
UI: Dashboard sollte einen großen Button haben, der direkt zu den Ressourcen führt.

### ISSUE THREAD

**Issue by ccupb** [tiloman/simren-issues#126]
UI: Dashboard sollte einen großen Button haben, der direkt zu den Ressourcen führt. Zur Zeit muss man oben über den Reiter Ressourcen hovern und dann auf Ressourcen klicken. Man könnte z.B. einen großen Button "Ressourcen" neben den Button "Überzogene Buchungen" platzieren.

**Comment by tiloman** [comment]
Ein User kommt nun nach Login direkt auf die Ressourcen Seite. Admins landen weiterhin auf dem Dashboard. Ich denke das löst das Problem bereits, oder?
