### ISSUE TITLE
Buchungsbeginn kann nicht nachträglich nach vorne verlegt werden.

### ISSUE THREAD

**Issue by ccupb** [tiloman/simren-issues#127]
Beispiel: Heute ist der 01.01.24. Ich lege eine Buchung an, die am 14.01.24 starten soll. Ich erfahre im Verlauf des heutigen Tages, dass der Kunde die Artikel doch schon am 08.01.24 braucht. Wenn ich jetzt die geplante Buchung bearbeite, erlaubt der Date Picker mir nicht ein früheres Datum als den 14.01.24 auszuwählen.

**Comment by OneOfTwelve** [comment]
Man kann die Buchung auch vor Ihrem Beginn ausgeben. Löst dies ggf. Das Problem?

**Comment by tiloman** [comment]
Eine Buchung nachträglich nach vorne zu verlegen ist nun möglich.
