### ISSUE TITLE
Bereich "Verfügbarkeiten" verbessern

### ISSUE THREAD

**Issue by ccupb** [tiloman/simren-issues#129]
Wenn nur eine Ressource ausgewählt ist, wäre eine Monatsansicht schön.
Wenn eine, oder mehrere Ressourcen ausgewählt sind, sollte es eine Option geben, statt der Kalenderwochen einen beliebig langen Zeitstrahl anzuzeigen, sodass man horizontal scrollen kann.
Es sollte die Möglichkeit geben (vielleicht per Checkboxen links neben den Ressourcen-Namen) Ressourcen auszuwählen und direkt von der Verfügbarkeiten-Ansicht in eine Buchung zu legen.

**Comment by tiloman** [comment]
aktuell gestalte ich die Seite um, da die anzeige ungenau war und nur die verfügbarkeit am Ende eines Tages angezeigt hat. Ich würde es (vorerst) bei den Kalenderwochen belassen, jedoch gerne navigationspfeile hinzufügen um schneller zur nächsten oder vorigen Woche navigieren zu können. 

Hier eine aktuelle Vorschau:
<img width="1290" alt="image" src="https://github.com/user-attachments/assets/fc5717a6-a16f-43d4-9e73-89ad05b07540">

**Comment by tiloman** [comment]
die neue verfügbarkeitsansicht ist online
