### ISSUE TITLE
Buchungen default-Sortierung chronologisch + wählbar

### ISSUE THREAD

**Issue by ccupb** [tiloman/simren-issues#131]
Die default-Sortierung der geplanten Buchungen im Tab Buchungen sollte chronologisch nach Ausgabezeitpunkt sein.
Die default-Sortierung der laufenden Buchungen im Tab Buchungen sollte chronologisch nach Rückgabezeitpunkt sein.
Es wäre auch noch praktisch, wenn man die Sortierung frei wählen könnte.

Zur Zeit scheinen die Buchungen gar nicht sortiert zu sein.

**Comment by tiloman** [comment]
<img width="1389" alt="image" src="https://github.com/user-attachments/assets/2174a6b7-9ea6-4926-b6af-28f5856c8aa2">
Sortierung ist nun möglich und wird für laufende und kommende Buchungen automatisch angepasst. Default ist nach Startdatum aufsteigend.
