### ISSUE TITLE
User: Passwortänderung nicht möglich

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#138]
## Problem:
Die Einstellung sein Passwort zu ändern ist nicht auffindbar. In unserem Fall betrifft dies logischerweise nur die Accounts welche direkt in Simren angelegt sind und sich mit ihrer Mail und dem Passwort direkt einloggen.

## Lösung:
Einbauen einer Passwort ändern Funktion unter "Meine Einstellungen" für direkte Accounts.

**Comment by tiloman** [comment]
fixed
