### ISSUE TITLE
Vorlaufzeit wird bei Start-Zeit einer Buchung nicht berücksichtigt.

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#143]
Steht in Verbindung mit https://github.com/tiloman/simren-issues/issues/9

Die bei einer Buchung vorgeschlagene Start-Zeit im Uhrzeit-Feld berücksichtigt leider nicht die Vorlaufzeit. Diese beträgt bei uns 2160 Minuten (36h). Beim Setzen der vorausgewählten Uhrzeit wird leider nicht geprüft, ob diese innerhalb der Vorlaufzeit liegt. Das ist unschön und führt dazu, wenn man sie einfach übernimmt, zu einer Fehlermeldung: "Gaming-Laptop muss mindestens ein Tag vorher gebucht werden." (Wieso "36h" als "mindestens ein Tag vorher" interpretiert wird, ist ne andere Baustelle ;).

**Comment by tiloman** [comment]
Die Vorlaufzeit wird nun berücksichtigt bei der Vorauswahl.
