### ISSUE TITLE
Anzeige Telefonnummer von Benutzer fehlerhaft

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#148]
Ich habe unter https://xyz.simren.de/users/3/edit eine Telefonnummer für einen Benutzer hinterlegt im Format 012345-xy-11111.

Auf der Benutzerseite sieht das dann wie folgt aus:
![Firefox_Screenshot_2024-12-05T14-27-52 617Z](https://github.com/user-attachments/assets/109cc81e-4564-4a95-b1a6-3f0ea37af462)

Spannend ist dabei, dass oben rechts die aktuelle Telefonnummer angezeigt wird (soll das so weit rechts alleine stehen?) und links unter dem Namen über "angemeldet seit:" die Telefonnummer, die davor mal als Telefonnummer im Profil hinterlegt wurde, dann aber eigentlich überschrieben wurde und nirgendswo mehr auftauchen sollte.

**Comment by mimosel** [comment]
Spannend ist auch, dass links bei dem alten Eintrag, der eigentlich weg sein sollte, die Vorwahl fehlt

**Comment by tiloman** [comment]
Im rechten Bereich befindet sich die Info, die man als Admin für das Userprofil hinterlegen kann. Sollte ein User beispielsweise keine Telefonnummer hinterlegt haben, so kann man als Admin dort eine hinterlegen. Die Telefonnummer direkt (also das, was im linken Bereich angezeigt wird), kann nur der User selbst editieren. 


> Spannend ist auch, dass links bei dem alten Eintrag, der eigentlich weg sein sollte, die Vorwahl fehlt
Das kann ich so nicht nachvollziehen.

**Comment by mimosel** [comment]
Ich hatte die Telefonnummer mit zwei Minuszeichen in der Nummer eingeben: 01356-28-435345 . Liegts vielleicht daran?

**Comment by tiloman** [comment]
Geht bei mir. Mit genau der Nummer

**Comment by mimosel** [comment]
Okay, ich kann es auch nicht mehr rekonstruieren. Vielleicht habe ich mich auch einfach getäuscht? Von mir aus kann der issue geschlossen werden.
