### ISSUE TITLE
Feature Request: Suchfunktion Optimierung

### ISSUE THREAD

**Issue by thupb** [tiloman/simren-issues#152]
Die Möglichkeit, dass die Suche auch weitere Angaben der jeweiligen Ressourcen in die Suche mit einbezieht (z.B. Hersteller). Im Moment wird ja nur nach Ressourcenname gesucht.
Hierbei wäre aber auch noch eine Optimierung die Suche unabhängig von der Reihenfolge der eingegebenen Suchbegriffe zu ermöglichen (Beispiel: Wenn ich nach Apple iPad suche finde ich die Ressource, da sie genau so heißt, suche ich aber nach iPad Apple wird nichts mehr gefunden, da die Reihenfolge der Begriffe nicht stimmt, obwohl beide im Ressourcennamen stecken)

**Comment by mimosel** [comment]
Nahezu identisch zu https://github.com/tiloman/simren-issues/issues/111

**Comment by thupb** [comment]
Hab ich wohl beim Abgleich übersehen. Dann kann ichs ja gleich wieder schließen
