### ISSUE TITLE
(R-)Admin: Benutzerauswahl uneindeutig bei gleichem Vor- und Nachnamen

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#18]
### Problem:
Wenn man ein Geräteverwalter auswählt oder eine Ressource für jemanden anderen Buchen will weiß man nicht welcher Nutzer der richtige ist falls es weitere Nutzer mit identischem Vor- und Nachnamen gibt.

### Lösung:
- Mailadresse daneben anzeigen lassen.
- einführen eines eindeutigen Usernamen (würde ich persönlich bevorzugen)

**Comment by tiloman** [comment]
Die Mail Adresse wird zusätzlich mit angezeigt
