### ISSUE TITLE
Enddatum Sperrzeiten

### ISSUE THREAD

**Issue by NetzwerkMedienSHK** [tiloman/simren-issues#25]
Bei den Sperrzeiten für Ressourcen ist das Enddatum etwas verwirrend. Besser wäre wie bei den Schlüsselcodes "Gültig bis einschließlich"

**Comment by tiloman** [comment]
Kannst du das noch konkretisieren? Die Idee ist ja, dass man eine Sperrzeit für Ferien o.ä. einrichtet. Da ist ja in der Regel leichter die konkreten Daten einzugeben als das Anfangsdatum + x Tage. 

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/47814142/216315187-d30a94c3-5516-476c-9b94-127fa0e59817.png">

**Comment by NetzwerkMedien-SHK** [comment]
Es geht darum, dass wenn ich den 02. Februar als Enddatum angebe, dann ist die Sperrzeit nur bis morgens 0:00 Uhr am 02.02.. Das heißt der 02.02. selbst ist nicht mehr gesperrt. Wenn ich eine Sperrzeit einrichten möchte, die vom 01.02. bis einschließlich 02.02. gehen soll, dann muss ich den 03.02. als Enddatum angeben. Das ist jedoch in der Nutzung verwirrend und führt zu Missverständnissen, bis wann genau die Sperrzeit gilt. 
Für uns wäre zum Beispiel einfacher das Enddatum der Sperrzeit mit der Uhrzeit 23:59 Uhr zu versehen. Oder die Uhrzeit auch manuell einstellen zu können.

**Comment by tiloman** [comment]
Alles klar, das ist tatsächlich missverständlich. Ich werde das abändern, dass auch das Enddatum noch mit inkludiert wird.

**Comment by NetzwerkMedien-SHK** [comment]
Super, vielen Dank! :)

**Comment by mimosel** [comment]
Sorry, dass ich das noch mal anmerke: Aber das ist doch gar nicht gefixed. Wenn ich den 01.05. sperren will, muss ich im Dialog nach wie vor den Folgetag auswählen.

![Image](https://github.com/user-attachments/assets/0221ef01-c13d-4991-adbe-258de28015e6)

**Comment by mimosel** [comment]
siehe hierzu auch https://github.com/tiloman/simren-issues/issues/205
