### ISSUE TITLE
Admin / User: Ausleihe auch in Zeitraum möglich zu dem alle Geräte gebucht sind

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#26]
### Problem:
Ressourcen können in einem Zeitraum gebucht werden in welchem alle Artikel der Ressource bereits gebucht/ausgegeben sind.

### Lösung:
Buchungen in Ausgebuchten Zeiträumen verhindern und dem User mitteilen ab wann er die gewünschte Ressource in der gewünschten Anzahl wieder buchen kann.

**Comment by tiloman** [comment]
konnte nicht reproduziert werden trotz umfangreicher tests. Wird daher geschlossen.
