### ISSUE TITLE
User: Footer in eigener Instanz zu umfangreich

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#29]
### Problem:
In der eigenen Instanz ist im Footer der Reiter "Produkt" etwas störend / nicht relevant für die Nutzer.

### Lösung:
Reiter "Produkt" ausblenden und ggf. den "Hilfe"-Reiter auf 2 Spalten aufteilen, dadurch würde er auch etwas schlanker daher kommen.

**Comment by tiloman** [comment]
Der Footer wird komplett entfernt.
