### ISSUE TITLE
(R-)Admin: Ausgabe mehrerer identischer Geräte - gleiche Artikel vorausgewählt

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#30]
### Problem:
Hat jemand mehrere Artikel der gleichen Art gebucht und man möchte diese Ausgeben wird für alle Artikel der gleichen Ressource der identische Artikel vorausgewählt, man muss dann händisch die Vorauswahl ändern.

### Lösung:
Beim Aktuellen Ranking bei jedem Artikel der Ressource um ein Artikel weiter nach hinten im Ranking gehen.

**Comment by tiloman** [comment]
erledigt
