### ISSUE TITLE
User: Kernfunktion geht nach Login etwas unter

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#31]
### Problem:
Nach dem Login landet man auf dem Dashboard, den meisten Platz auf dem Dashboard nehmen Elemente ein welche eigentlich nicht das wichtigste für den Nutzer sind. Der Nutzer loggt sich nach meinem Verständnis primär zum Buchen einer Ressource ein. 
Auf dem Dashboard hat man ganz unten eine kleine Übersicht über die Ressourcen man muss erst in die Navigation um die eigentliche Funktion nutzen zu können.
Vergleichbar wäre dies wenn man bei Amazon erst in der Übersicht zu "Mein Konto" landet und nicht direkt im Shop.

### Lösung:
1. "Deine Bevorstehenden Buchungen" in die Navigation packen zum Beispiel in ein Reiter "Meine Buchungen".
2. An die stelle der bevorstehenden Buchungen "Die beliebtesten Ressourcen" setzen.
3. Die Ressourcen Übersicht aus dem Menüpunkt "Ressourcen" direkt drunter unterbringen.

**Comment by tiloman** [comment]
die startseite für user ist geändert
