### ISSUE TITLE
Admin: Maximales Zeichenlimit der Einheit zu niedrig

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#43]
### Problem:
Name der Hochschule kann nicht ausgeschrieben werden da zu lang. Eine Gekürzte Version verstößt leider gegen unser Corporate Wording.

### Lösung:
Zeichen Limit für Institutionsnamen auf mindestens 35 Zeichen Setzen.

**Comment by tiloman** [comment]
Zeichenzahl erhöht
