### ISSUE TITLE
Admin: Nachträglich ermöglichen mehrere Artikel auf einmal zur Ressource hinzuzufügen

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#46]
### Problem:
Hat man eine Ressource angelegt muss man jeden Artikel einzeln Anlegen.

### Lösung:
Ermöglichen die Funktion hinter "Mehrere identische Ressourcen vorhanden?" aus dem Erstellverlauf einer Ressource auch nachträglich zu nutzen.

**Comment by ccupb** [comment]
+1

**Comment by tiloman** [comment]
Ist umgesetzt: Ressource ansehen -> Zugehörig -> Mehrere Artikel anlegen
