### ISSUE TITLE
(R-)Admin: Hinweis für die Rücknahme anzeigen.

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#48]
### Problem:
Wir haben Geräte bei deren Rückgabe auf spezielle Punkte geachtet werden muss die je nach Gerät unterschiedlich sind. Leider werden diese Oft in der Hektik vergessen oder neue Aushilfen kennen diese Punkte nicht alle.

### Lösung:
Rücknahmehinweise als Popup für die Person welche ein Gerät zurücknimmt welche, bevor das Gerät zurück genommen werden kann, bestätigt werden müssen.

**Comment by tiloman** [comment]
<img width="658" alt="image" src="https://github.com/tiloman/simren-issues/assets/47814142/ec993b78-5a7e-49c5-a87a-6d498d2dada6">
kann jetzt in den geräteeinstellungen eingestellt werden und wird bei ausgabe und rückgabe als tooltip angezeigt

**Comment by OneOfTwelve** [comment]
Leider gehen diese Wichtigen Hinweise unter.
Aus unserer Sicht wäre es Sinnvoll wenn diese Wirklich auf Popen als Fenster als Overlay über der weiteren Ausgabe Zurücknahme. welches Nur 1 Button zum schließen hat "Bestätigen"/"OK". Natürlich wäre es gut wenn man dieses Popup über die aktuellen Fragezeichen nochmal öffnen könnte bei bedarf.

Hierzu zählen Dinge wie das daran gedacht wird, darauf zu achten das Geräte ausgeschaltet sind, Batterien ausgetauscht werden, Akkus geladen werden oder das bei Spiegelreflexkameras der Schutzdeckel auf dem Objektiv sitzt.
