### ISSUE TITLE
Admin: "Ressourcenname zu lang" Fehler selbst nach Kürzung des Namen

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#49]
### Problem:
Gibt man in das Feld "Name" einer neuen Ressource einen zu langen Namen an erhält man eine Fehlermeldung, welche leider nicht verschwindet wenn man den Namen entsprechend kürzt.

### Lösung:
Überprüfung mit dem neuen Namen durchführen und somit Fehlermeldung nicht mehr anzeigen.

**Comment by tiloman** [comment]
gefixt
