### ISSUE TITLE
(R-)Admin: Sperrung von Usern ermöglichen

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#5]
### Problem:
Nutzer welche Geräte nicht zurückgegeben haben bzw. beschädigt haben können weiter Geräte buchen und ausleihen. Wenn die Person welche die Buchung ausgibt nicht daran denkt / die ausleihende Person nicht kennt oder auch nichts davon weiß hat man ggf. mehr defekte Geräte bzw. mehrere welche nicht zurückkommen.

### Lösung:
Admin (ggf. auch R-Admin) ermöglichen User dauerhaft oder auch zeitweise zu sperren, so dass diese keine weiteren Ausleihen tätigen können.

**Comment by tiloman** [comment]
Admins können User nun sperren
