### ISSUE TITLE
(R-)Admin: Zugehörige Artikel sortieren

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#51]
### Problem:
In dem Reiter "Zugehörig" einer Ressource sind die Artikel scheinbar chaotisch angelegt.

### Lösung:
Alphabetische Sortierung für die Artikel wählen anstelle der Artikel ID welche es im Moment vermutlich ist.

**Comment by tiloman** [comment]
Aktuell ist es so sortiert, dass sowohl alphabetisch als auch numerisch sortiert wird was meiner Meinung nach am sinnvollsten ist in diesem Fall. 
<img width="170" alt="image" src="https://user-images.githubusercontent.com/47814142/231262718-a376e55d-bd1f-456f-ac2c-1790a4674297.png">

Eine Alternative sortierung nur basierend auf alphabetischer Sortierung wäre unschön sobald es mehr als 10 Artikel gibt. 
<img width="148" alt="image" src="https://user-images.githubusercontent.com/47814142/231262787-b080004b-f103-42c2-b811-ede810a32f96.png">
Solange Name (Kamera) und Nummer (5) nicht getrennt abgespeichert werden ist die aktuelle Lösung meiner Meinung nach die beste. Ich bin für alternative Vorschläge offen.

**Comment by tiloman** [comment]
So, nun sollte es besser aussehen. bitte nochmal prüfen.
