### ISSUE TITLE
Admin: Emailbenachrichtungen trotz deaktivierung

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#53]
### Problem:
Obwohl in den Benachrichtigungseinstellungen die Häkchen für die Adminbenachrichtigungen per Mail deaktiviert sind. Bekommen wir trotzdem Mails zum Beispiel über Änderungsanfragen oder Kommentare.

### Lösung:
Bitte Mails nur so versenden wie dies auch in den Benachrichtigungseinstellungen festgelegt ist.

**Comment by tiloman** [comment]
Bei den Mails für die Änderungsanfragen gab es einen Fehler den ich korrigiert habe.

Was die Benachrichtigungen für Kommentare angeht habe ich nichts feststellen können. Es gibt für Admins eine globale einstellung und auch für Ressourcenadmins ebenso. Nach dem anlegen einer Buchung wird für Admins/Ressourcenadmins eine subscription für die kommentare erstellt (wenn die einstellung aktiviert ist). D.h. für ältere Buchungen gehen Mails raus wenn zum Zeitpunkt der Buchungserstellung die Benachrichtigungen aktiviert waren. Neue Buchungen betrifft das nicht.
