### ISSUE TITLE
User: Links zur lokalen Anmeldung Ausblenden

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#56]
### Problem:
Die Links "Passwort vergessen", "Keine Bestätigungsmail bekommen?" und "Noch keinen Account? Registriere dich" sind irreführend wenn man sich über seine Hochschuldaten anmeldet.

### Lösung:
Unter Administration -> Allgemein ein Toggle einstellbar machen um diese Sachen auszublenden und Studierende nicht irre zu führen.

**Comment by tiloman** [comment]
Es gibt nun zwei toggle Möglichkeiten: Neuregistrierungen per Mail verhindern und Logins verhindern.
