### ISSUE TITLE
Buchungskalender für Vergangenheit ausgrauen

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#57]
### Problem:
Bei der Raumbuchung kann nach dem Zeichnen wann man den Raum nutzen will das Zeitfenster in einen vergangenen Tag geschoben werden sofern der Raum dort offen war und die Buchung mit diesen Daten abschließen.

### Lösung:
Vergangene Tage ebenfalls aus grauen und bei dem Versuch in dieser Zeit zu Buchen eine Fehlermeldung anzeigen.

**Comment by tiloman** [comment]
> Das Startdatum liegt in der Vergangenheit

Problem besteht nicht mehr. Im Frontend zwar möglich das Zeitfenster in die Vergangenheit zu verschieben, aber die Buchung so abzuschließen nicht.

**Comment by tiloman** [comment]
Erledigt
