### ISSUE TITLE
Admin: Suche nach Benutzer funktioniert nicht

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#62]
### Problem:
In der Übersicht über alle Benutzer werden diese nicht gefunden wenn man nach dem Vor- oder Nachnamen sucht.

### Lösung:
Suche verbessern bzw. ermöglichen nach (Teil)Namen zu suchen.

**Comment by tiloman** [comment]
Bislang wurde groß- und kleinschreibung berücksichtigt. Das wird jetzt ignoriert. Damit sollte es wie gewünscht funktionieren.
