### ISSUE TITLE
(R-)Admin: Buchung teilweise zurücknehmen

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#63]
### Problem:
User Leihen mehrere Geräte mit einer Buchung aus bringen aber nicht alle auf einmal zurück.
Die Rückgabe einzelner Elemente einer Buchung kann aktuell nicht erfasst werden.

### Lösung:
Bei der Rücknahme eine Liste (Checkboxes) aller in der Buchung vorhandenen Items anzeigen, welche standardmäßig checked sind.
Die ausgewählten Elemente werden zurückgenommen. Wenn ein Gerät fehlt kann die checkbox deaktiviert werden.

**Comment by mimosel** [comment]
+1

**Comment by mimosel** [comment]
@OneOfTwelve Wie geht Ihr aktuell mit nur teilweise zurückgegebenen Buchungen um?

**Comment by OneOfTwelve** [comment]
> @OneOfTwelve Wie geht Ihr aktuell mit nur teilweise zurückgegebenen Buchungen um?

Aktuell erlauben wir nur sehr begrenzt Buchungen mit mehreren Geräten auf einmal da uns das zu umständlich ist in jedem Gerät zu erlauben das es mit jedem anderen Gerät auf einmal ausgeliehen werden darf.

In der Regel nehmen wir unvollständige Rückgaben von Buchungen nicht an.

Wir haben aber auch schon die ganze Buchung zurückgenommen und die übrigen Geräte erneut ausgegeben.
Oder die Teilrückgabe auf Papier oder in den Kommentaren zur Buchung vermerkt.

**Comment by tiloman** [comment]
<img width="578" alt="image" src="https://github.com/tiloman/simren-issues/assets/47814142/09cf3f47-3366-484c-9ae8-2d2cef8d6ccc">

Teilrückgabe ist jetzt möglich
