### ISSUE TITLE
Webseite Bild und Text zur Unterschrift noch Beworben

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#66]
### Problem:
Auf der Simren Webseite ist noch das alte Unterschriftenverfahren beworben.
![image](https://github.com/tiloman/simren-issues/assets/18131550/6e5064fc-4f04-4206-8e9d-245183b24cd6)

### Lösung:
Beschreibung durch eine des neuen Code Verfahrens ersetzen.

**Comment by tiloman** [comment]
Danke, war auch noch auf meiner Liste :)
