### ISSUE TITLE
(R-)Admin: Anlegen von Buchungen für andere und sofortige Ausgabe nicht mehr möglich

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#67]
### Problem:
Bei uns kommen teilweise Kunden die schnell ein Gerät brauchen an. Bisher war das so, dass wir dann die Buchung angelegt haben und die Buchung gleich ausgegeben haben. Der Kunde hat dann gleich auf unserem Touchscreen unterschrieben und wir konnten den Artikel sofort ausgeben. Wenn wir nun allerdings für eine andere Person buchen bekommt diese nun den code gemailt und wir können den Artikel nicht mehr gleich ausgeben. Die Person müsste nun auf die Mail zugriff haben oder sich in Simren einloggen womit der Zeitvorteil wieder hinfällig wäre.

### Lösung:
(R-)Admins erlauben Ressourcen auch ohne Code auszugeben. (Kann auch bisschen Zeit sparen wenn man den Kunden kennt)

**Comment by tiloman** [comment]
Ok, ich sehe das Problem. Ich überlege mir wie es am besten gelöst werden könnte. Spontan fällt mir ein:

- den Code zusätzlich auch an den Admin zu schicken/anzuzeigen der die Buchung angelegt hat (wenn die Buchung für jemanden angelegt wurde)
- eine Sofortausgabe-Option: man wählt als admin direkt das verfügbare Inventar und im Hintergrund wird die Buchung und auch die Ausgabe in einem Schritt angelegt

Generell den Code zu überspringen halte ich für schwierig weil es die Sicherheit für den User ist, dass Admins nicht im Namen des users ausgaben anlegen können. 
Es soll ja ein beidseitiger Handshake sein: Code gegen Gegenstände. Das eine soll ohne das andere nicht gehen.

**Comment by tiloman** [comment]
>(R-)Admins erlauben Ressourcen auch ohne Code auszugeben. (Kann auch bisschen Zeit sparen wenn man den Kunden kennt) 
@OneOfTwelve auch das habe ich für euer Team zum testen freigeschaltet. Ich würde mich über ein Feedback freuen.

**Comment by OneOfTwelve** [comment]
> > eine Sofortausgabe-Option: man wählt als admin direkt das verfügbare Inventar und im Hintergrund wird die Buchung und auch die Ausgabe in einem Schritt angelegt
> 
> Ich habe die Funktion hinzugefügt und für euer Team zum testen freigeschaltet. @OneOfTwelve

Ok, Danke.
Ich habe den Button erst etwas suchen müssen. Mein Arbeitskollege und ich würden ihn intuitiv eher unter der Seite "Ressourcen" erwarten.

**Comment by OneOfTwelve** [comment]
> > (R-)Admins erlauben Ressourcen auch ohne Code auszugeben. (Kann auch bisschen Zeit sparen wenn man den Kunden kennt)
> 
> @OneOfTwelve auch das habe ich für euer Team zum testen freigeschaltet. Ich würde mich über ein Feedback freuen.

Danke, sehr schön bei unseren wenigen Testbuchungen eben funktionierte dies gut.

**Comment by tiloman** [comment]
> Leider bekommen wir wenn wir diese Funktion nutzen wollen die meldung "Einverständnis nicht gegeben...."

Ist gefixt.

**Comment by OneOfTwelve** [comment]
Ok Danke. Der schnelle Test hat funktioniert. Bitte bei dem Nutzerauswahlfeld noch die Mailadressen hinter dem Namen anzeigen um mehrere Nutzer mit gleichem Vor- und Nachnamen unterscheiden zu können.

**Comment by tiloman** [comment]
erledigt
