### ISSUE TITLE
(R-)Admin: Einmalcodeeingabe Format vom Eingabefeld ändern

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#68]
### Problem:
Das Feld "Einmalcode eingeben" ist nicht vom Typ "number". Dadurch werden eingaben nicht Browserseitig Validiert und weisen gleich auf einen Eingabefehler hin außerdem öffnet sich an Touchbildschirmen erst die Texteingabe und nicht gleich das Nummernfeld.

### Lösung:
- Typ des Eingabefeldes von "text" auf "number" umstellen.
- Values auf "min: 100000" und "max: 999999" stellen

**Comment by tiloman** [comment]
kommt.
