### ISSUE TITLE
Registrierungsformular: unnötige Fettung wegnehmen

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#71]
Beim Registrierungsformular ist der Eintrag zur optionalen Telefonnummer gefettet. Das ist nicht nachvollziehbar, bitte entfetten.

**Comment by tiloman** [comment]
Im klassischen Registrierungsformular gibt es das Feld nicht. Im Profil bearbeiten ist das Label nicht fett und sonst finde ich die entsprechende Stelle auch nicht. Ein Screenshot wäre hilfreich. Danke

**Comment by tiloman** [comment]
Danke. Fix mit nächstem Release
