### ISSUE TITLE
Studi-User hat bei der Ressourcenansicht keine Kalenderübersicht

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#72]
Ein studentischer User hat in der Ressourcenansicht keine Kalenderübersicht, wie sie der Admin als Monatsansicht sieht. 
Es wäre schön, wenn auch Studis eine Monatsansicht für die von Ihnen gewünschte Ressourcen hätten, dort dürften Studis natürlich sehen können, wer ein Gerät ausgeliehen hat, sondern nur wann es schon ausgeliehen ist. Grundsätzlich sollte die Anzahl an noch verfügbaren Geräten einer Ressource angezeigt werden.

**Comment by tiloman** [comment]
Dies kann unter `xyz.simren.de/booking_settings` eingestellt werden.

<img width="1326" alt="image" src="https://github.com/tiloman/simren-issues/assets/47814142/1fb160f1-5a7a-4b95-a9db-536626ca839d">

**Comment by mimosel** [comment]
Ich habe das jetzt mal angeschaltet, sehe aber keine Kalenderansicht. Wo sollte die denn zu sehen sein?
