### ISSUE TITLE
bei Ressourcenbuchung kann Kategorie weggeklickt werden -> Fehlermeldung

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#73]
Klickt man bei der Ressourcenbuchung die Kategorie weg und schickt das Formular ab, erhält man eine Fehlermeldung.
![grafik](https://github.com/tiloman/simren-issues/assets/129038745/aea0d2cd-dc76-4895-bf4d-6a496653bd52)

![grafik](https://github.com/tiloman/simren-issues/assets/129038745/047aad1b-6b76-4bdb-ba75-3b41833e9b90)

**Comment by tiloman** [comment]
Kann ich so nicht nachstellen. 

Was ich getan habe:
- Erstellen einer Buchung über den Buchungsbutton in der Ressourcenübersicht
- Ressource im Dropdown abgewählt und das Formular mit einem leeren Dropdown abgeschickt. 
- Es erscheint eine Meldung dass Ressourcen ausgewählt werden müssen 

-> Das wäre das erwünschte Verhalten.

Gerne nochmal probieren und die Schritte detailliert festhalten

**Comment by mimosel** [comment]
Ich kann das in der Tat auch nicht mehr rekonstruieren. Ich habe wohlgemerkt nicht nur die Ressource im Dropdown abgewählt, sondern mit dem "Knopf" ganz rechts am Feld das ganze Feld weggeklickt. Dann erhalte ich die Fehlermeldung "Type ids muss ausgefüllt werden". Wieso kann man überhaupt das ganze Feld wegklicken?
![image](https://github.com/tiloman/simren-issues/assets/129038745/bcf1ec03-6ba5-4e5c-abf4-326494ab835b)

**Comment by tiloman** [comment]
Das erste Feld ist nun nicht mehr wegklickbar.
