### ISSUE TITLE
Gerät wird als Raum bezeichnet

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#74]
Wenn man als Admin ein Gerät bearbeitet (...simren.de/devices/2/edit ), wird das Gerät bei der Rechteverwaltung als "Raum" bezeichnet. Bitte beheben.
![grafik](https://github.com/tiloman/simren-issues/assets/129038745/ec603289-a006-48b0-bc82-406b217eba73)

**Comment by tiloman** [comment]
Danke, übersetzungsfehler. Ist im nächsten Release gefixt.
