### ISSUE TITLE
Anlegen einer Gerätekategorie fehlerhaft

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#77]
Wir haben eine dritte / bzw. vierte Gerätekategorie anlegen wollen. (z.B. „Mikrofone“), aber beim Abspeichern wird diese neu angelegte Kategorie nicht dem/den Geräten zugewiesen. 
Studi-User können diese Geräte nicht sehen. Als Admin tauchen die Geräte unter Ressourcen aber auf (hier Gerätegruppe „Mikrofon“)
![grafik](https://github.com/tiloman/simren-issues/assets/129038745/1b00782b-0645-40f7-8349-e32524ce8cd5)

und als Admin sehe ich unter den Admin-Infos (https://xyz.simren.de/types/4):
![grafik](https://github.com/tiloman/simren-issues/assets/129038745/0b4276ca-be1a-44c0-9a27-bc598b628d18)

**Comment by tiloman** [comment]
Wie auch schon der Hinweis im Screenshot zeigt:
> Noch keine Gruppen zugewiesen. Deine Ressource ist für Nutzerinnen noch nicht buchbar. 

Solange die Ressource nicht in der Gruppe `Alle` oder einer anderen ist (in der dann die entsprechenden User sind), ist sie nicht sichtbar (und buchbar). 
Ich werde den Hinweistext imm nächsten Release anpassen.

**Comment by mimosel** [comment]
Ich bin mir nicht sicher, ob ich das verstehe. Wir haben eine neue Ressource, vom Typ Gerät angelegt. Diese neue Ressourcen haben wir dann über "Add neue Kategorie" (siehe Screenshot) einer Kategorie zugefügt.
![grafik](https://github.com/tiloman/simren-issues/assets/129038745/440840ae-f607-454d-981c-2252512171bb)
Wir dachten, dass das Gerät dann auch automatisch buchbar ist.

Wenn ich das richtig verstehe, muss es aber auch einer Gruppe (unter Rechteverwaltung, ganz unten im Screenshot) zugewiesen werden? Sollte es dann hier nicht so sein, dass das Feld "Gruppen" evtl. ein Pflichtfeld wird oder dort ein default-Wert vorausgewählt ist?

**Comment by tiloman** [comment]
> Wenn ich das richtig verstehe, muss es aber auch einer Gruppe (unter Rechteverwaltung, ganz unten im Screenshot) zugewiesen werden?

Das ist richtig. Die Kategorie hat erstmal nur was mit der Darstellung auf der Ressourcenseite zutun, jedoch nichts mit der Buchbarkeit. Die Buchbarkeit wird in der Rechteverwaltung organisiert. 

> Sollte es dann hier nicht so sein, dass das Feld "Gruppen" evtl. ein Pflichtfeld wird oder dort ein default-Wert vorausgewählt ist?

Ich würde es nicht als Pflichtfeld definieren, da es durchaus auch Szenarien geben kann in denen ausschließlich Admins einen Gegenstand buchen können und der für User nie sichtbar sein soll. Ein Standardwert wäre denkbar für die Gruppe `Alle`, allerdings kann es dann auch schnell dazu kommen dass versehentlich Geräte der Gruppe hinzugefügt werden die nicht für Alle bestimmt sind. Daher soll hier bewusst eine Entscheidung getroffen werden meiner Meinung nach.

**Comment by mimosel** [comment]
Wenn bewusst eine Entscheidung getroffen werden soll, wäre es dann nicht gut, das Feld doch als Pflichtfeld zu definieren (dann wird man ja gezwungen, bewusst eine Entscheidung zu treffen) und einfach eine Gruppe "Admins" einzuführen?
