### ISSUE TITLE
Reservierung von Geräten und Zubehör

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#78]
Warum kann ich beim Reservieren (https://xyz.simren.de/bookings/new?type=3) bei Kategorie „Leinwand 2“ selbige als Zubehör hinzufügen? Ich habe beim Anlegen der Kategorie lediglich „Projektor 2“ als Zubehör angegeben

![grafik](https://github.com/tiloman/simren-issues/assets/129038745/ac72053e-ba29-4a3b-8427-c1113ac911c7)

Hier wäre ein Warenkorb besser. Standardmäßig sollen alle Geräte als „Zubehör“ zusammen ausgeliehen werden können.

**Comment by mimosel** [comment]
@tiloman sagt dazu:

> Ja. Nutzer können das nur wenn Ressourcen speziell als Zubehör deklariert wurden. So ist zum Beispiel gewährleistet dass zur GoPro ein anderes Stativ gehört als zur DSLR. Wenn die komplette Auswahl zur Verfügung stünde, könnte es schnell auch verwirrend für User sein da die Produkte vielleicht nicht kompatibel gewählt werden.

**Comment by tiloman** [comment]
> „Leinwand 2“ selbige als Zubehör
Das geht, weil bei der ressource angegeben wurde, dass mehrere Geräte gleichzeitig ausgeliehen werden können.

**Comment by tiloman** [comment]
Ich werde eine Rolle einführen die man einzelnen Usern geben kann. Diese User können dann alle Ressourcen miteinander kombinieren.

**Comment by mimosel** [comment]
Gibt es hier einen Zeitplan für?

**Comment by tiloman** [comment]
Ist umgesetzt. 
Administration - BenutzerInnen - Edit User - unten findet man Rollen. Dort die Rolle `Poweruser` vergeben. Der User hat daraufhin in der Buchungsansicht die Option alle Geräte miteinander zu kombinieren.
