### ISSUE TITLE
Abholcode als Admin nicht einsehbar

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#79]
Als Admin sehe ich weder in der Bestätigungs-E-Mail noch in der „Buchung anzeigen“ (https://xyz.simren.de/bookings/7) Übersicht einer neu angefragten Buchung den Abholcode.

**Comment by tiloman** [comment]
Der Abholcode ist ganz bewusst nur dem Kunden vorbehalten. Anhand des Abholcodes (den der Kunde dann nennt bei Abholung) kann der Admin dann die passende Buchung finden. Das System findet die Buchung daraufhin und verifiziert die richtigkeit. Daher sehe ich keinen Grund warum Admins den Code benötigen.

**Comment by tiloman** [comment]
<img width="403" alt="image" src="https://github.com/tiloman/simren-issues/assets/47814142/5a953d32-4383-44aa-8864-924fbd73524c">

Bei der Ausgabe den Abholcode skippen.

**Comment by OneOfTwelve** [comment]
Wenn die Nutzer ihr Handy dabei haben können diese auch in simren den Abholcode einsehen.
