### ISSUE TITLE
Admin: Unterbrechung der Öffnungszeit zulassen

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#8]
### Problem:
Mittagspausen oder allgemein regelmäßige Unterbrechungen können über die aktuelle Öffnungszeiteneinstellung nicht abgebildet werden. 

### Lösung:
Öffnungszeiten im Stil der Raumbuchung eingeben lassen.

**Comment by tiloman** [comment]
duplikat von #109
