### ISSUE TITLE
Anzeige von Abholcodes in Übersicht und Detailansicht

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#80]
Bei der Übersicht der Buchungen sowie bei der Detailansicht der einzelnen Buchungen wäre zudem eine Ansicht des Abholcodes (oder einer anderen Form einer eindeutigen Ticketnummer, die sowohl Ausleihende Person als auch Admin wissen) sinnvoll:
![grafik](https://github.com/tiloman/simren-issues/assets/129038745/b896ca93-8332-40b6-952f-bf1e50f1cac4)
Nur so finde ich bei der Rückgabe durch Studis schnell das zugehörige Ticket.

**Comment by mimosel** [comment]
Wäre es dann vielleicht möglich die Buchungsnummer ein wenig prominenter anzuzeigen und nicht so zu verstecken?

**Comment by tiloman** [comment]
Die Buchungsnummer ist in allen wichtigen Ansichten präsent und wenn man damit arbeitet weiß man schnell wo man sie finden kann. Es gibt auch Teams die sich nicht an der Buchungsnummer orientieren und für die sie keine wichtige Information darstellt. Ich würde sie daher so lassen.
