### ISSUE TITLE
Eingabe Abholcode wurde bei Ausleihe nicht erkannt

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#81]
Ich habe eine Buchung angelegt (Buchung #7) und mittels Abholcode die Geräte ausgegeben (https://xyz.simren.de/bookings/7). Trotzdem wird mir bei der Rückgabe angezeigt: Ausgabe erfolgte ohne die Eingabe eines Abholcodes.
![grafik](https://github.com/tiloman/simren-issues/assets/129038745/a154f140-a5bd-40a8-83a0-cf0a383e3d49)

**Comment by tiloman** [comment]
Ist im nächsten Release gefixt. Danke
