### ISSUE TITLE
Rücknahme: alles in Ordnung?

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#82]
Bei der Rücknahme (https://xyz.simren.de/bookings/7) kann ich nicht angeben, dass etwas nicht in Ordnung ist. Bei der Frage „Alles okay?“ reagiert das Feld nicht auf Eingaben.
![grafik](https://github.com/tiloman/simren-issues/assets/129038745/d3e0c186-47c9-4a5c-99f1-4647476eb1fa)

**Comment by tiloman** [comment]
![Kapture 2024-02-22 at 18 06 47](https://github.com/tiloman/simren-issues/assets/47814142/70c08af6-926d-4fee-baee-6d393543e9b7)

Es ist ein Dropdown feld was reagieren sollte. Welcher Browser wird verwendet?
