### ISSUE TITLE
Stornierung bereits abgeschlossener Buchungen

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#83]
Auch nach dem Zurücknehmen von Geräten habe ich als Admin die Option, die bereits abgeschlossene Buchung zu stornieren. 
![grafik](https://github.com/tiloman/simren-issues/assets/129038745/22c32561-468d-41e1-9a3b-7aef47e8f93f)
Warum wird "Stornieren" angezeigt? Wenn ich das auswähle, erscheint zudem eine Fehlermeldung:
![grafik](https://github.com/tiloman/simren-issues/assets/129038745/1d6828b3-3542-4533-b5ba-0467ac9232ae)

**Comment by tiloman** [comment]
Danke, Bug ist mit dem nächsten Release gefixt.
