### ISSUE TITLE
Verlängerung/Ausleihe von Geräten als Admin

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#84]
Als Admin sollte ich die Möglichkeit haben, Geräte / Buchungen auch über den angegebenen maximalen Zeitraum (hier bei uns im Test 3 Tage, https://xyz.simren.de/bookings/8/edit?type=3) hinaus zu verlängern.
![grafik](https://github.com/tiloman/simren-issues/assets/129038745/9e311278-6757-4e7e-93c9-c5d5c4c9514a)

**Comment by tiloman** [comment]
Bitte nochmals testen. Das ist eigentlich möglich als Admin sofern die Buchung nicht läuft. Ich denke hierbei handelt es sich eher um ein Stylingproblem (Daten im nächsten Monat sind etwas dunkler dargestellt).
Wenn die Buchung läuft kann eine Verlängerungsanfrage gestellt werden.
