### ISSUE TITLE
Darstellung vieler Ausleihen im Kalender

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#86]
Ich habe 27 Audiorekorder ausgeliehen.
![grafik](https://github.com/tiloman/simren-issues/assets/129038745/fc69b151-5506-4404-b3ae-26adbcfc9c59)

Im Kalender wird mir das so aber nicht angezeigt. Ich sehe dort nur, dass ich einen Audiorekorder ausgeliehen habe.
![grafik](https://github.com/tiloman/simren-issues/assets/129038745/cd26dcb9-4d13-424d-8a6f-f497cb5e76e7)

Kann man das irgendwie aussagekräftiger machen? ein "+26" oder so würde ja schon helfen

**Comment by tiloman** [comment]
Ja, `+ X` wird drangehängt. Guter Hinweis, danke
