### ISSUE TITLE
Ressource kann nicht ausgegeben werden wg. fehlender id

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#87]
Ich habe eine Buchung getätigt.
![grafik](https://github.com/tiloman/simren-issues/assets/129038745/23a3bad4-c163-4146-82a8-7e46a6d7d566)

Die Ressource kann ich aber nicht ausgeben: 
![grafik](https://github.com/tiloman/simren-issues/assets/129038745/0f2a6f6b-032f-4dd1-8578-85f08cf96bf9)

![grafik](https://github.com/tiloman/simren-issues/assets/129038745/8b4e0ff7-48c4-4582-bf6a-aedb64c56aca)

Was ist hier passiert?

**Comment by tiloman** [comment]
Ja, das funktioniert nicht weil kein Projektor vorrätig ist (vermutlich ist eine Buchung überfällig). 
Im Backlog habe ich, dass ich in einem solchen Fall die Ausgabeseite anpasse und darauf verweise dass ein Artikel fehlt.

**Comment by tiloman** [comment]
> Im Backlog habe ich, dass ich in einem solchen Fall die Ausgabeseite anpasse und darauf verweise dass ein Artikel fehlt.

Done
