### ISSUE TITLE
Laufende Buchung wird als "bevorstehende Buchung" angezeigt

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#89]
Laufende Buchungen werden Nutzern als „bevorstehende Buchung“ angezeigt, wenn sie z.B. bereits vor dem ursprünglich geplanten Termin abgeholt werden:
![image](https://github.com/tiloman/simren-issues/assets/129038745/1f5b0164-38c0-40dc-bb58-e9660def8ad2)

**Comment by tiloman** [comment]
Ja das stimmt. Ich habe den Text angepasst: 'Deine laufenden und bevorstehenden Buchungen'

Mit dem nächsten Release online
