### ISSUE TITLE
User: Automatisch gewählte Uhrzeit bei Buchung am gleichen Tag liegt in der Vergangenheit

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#9]
### Problem:
Bei einer Buchung für sofort wird im Uhrzeit Feld immer der Beginn der Öffnungszeit des aktuellen Tages gewählt, wenn man schnell was buchen will für sofort läuft man zwangsläufig in die Fehlermeldung, dass der Beginn der Buchung in der Vergangenheit liegt.

### Lösung:
Vorausgewählte Uhrzeit auf aktuelle Uhrzeit + paar Minuten (evtl. 15min) setzen.

**Comment by mimosel** [comment]
+1

**Comment by tiloman** [comment]
umgesetzt

**Comment by mimosel** [comment]
Ich würde den Issue gerne nochmal aufmachen. Aktuell ist es so, dass das Uhrzeit-Feld leider nicht die Vorlaufzeit berücksichtigt. Diese beträgt bei uns 2160 Minuten (36h). Beim Setzen der vorausgewählten Uhrzeit wird leider nicht geprüft, ob diese innerhalb der Vorlaufzeit liegt. Das ist unschön und führt dazu, wenn man sie einfach übernimmt zu einer Fehlermeldung: "Gaming-Laptop muss mindestens ein Tag vorher gebucht werden." (Wieso "36h" als "mindestens ein Tag vorher" interpretiert wird, ist ne andere Baustelle ;).
