### ISSUE TITLE
Admin: API-Link öffnet im gleichen Tab

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#91]
### Problem:
Wenn man den Link zur API Dokumentation unter "Meine Einstellungen -> API Zugriff" klickt, öffnet sich dieser im gleichen Tab, somit ist man nicht mehr in den Einstellungen, wo sich auch der benötigte Token befinden würde. 

### Lösung:
Link in einem neuen Tab öffnen lassen.

**Comment by tiloman** [comment]
Ich nehme an du meinst den Link zu Swagger 
<img width="422" alt="image" src="https://github.com/tiloman/simren-issues/assets/47814142/95b2a2b0-b18d-4fac-a2db-271fbbf79ad2">

Habe ich abgeändert und ist bald online
