### ISSUE TITLE
Admin: API Token funktioniert in Swagger nicht

### ISSUE THREAD

**Issue by OneOfTwelve** [tiloman/simren-issues#92]
### Problem:
Gibt man in Swagger seinen API Key ein und führt dort einzelne GETs aus erhält man stehts die Meldung "Error: response status is 401" mit dem Inhalt "Not authorized. Contact us to get access.". Muss der API zugriff noch einmal extra freigeschaltet werden?

### Lösung:
Validierung des Zugriffs reparieren oder klarer in simren beschreiben wie das Recht für dem Zugriff erteilt werden kann.

**Comment by tiloman** [comment]
Hast du im Format `Bearer XXXXX` eingegeben wie hier beschrieben? 
https://simren.de/support/api-schnittstelle/

Eine extra Freischaltung bedarf es nicht mehr. Den Hilfe Artikel aktualisiere ich noch

**Comment by OneOfTwelve** [comment]
Ahhh das hatte ich überlesen. Wieso muss denn das "Bearer " vor den Key gestellt werden?
Gibt es fälle wo man das nicht braucht?
Wenn nein würde ich vorschlagen das einfach im API Feld mit vor den eigentlichen Key zu schreiben.

**Comment by tiloman** [comment]
Das hängt von der Art des Tokens ab und Swagger weiß nicht welche Authentifizierungsmethode ich verlange. Bei Abfragen via Postman zb braucht man das nicht, da dort einfach Bearer Token als Authentifizierungsmethode angegeben werden kann und Postman das dann übernimmt. 
Ich werde es daher auch so lassen und vllt noch die Beschreibung auf der Swagger seite optimieren.
