### ISSUE TITLE
Raumbuchung: "Wähle einen freien Zeitslot aus" lädt unendlich

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#93]
Ich habe einen Zeitplan angelegt. Ich habe einen Raum angelegt und diesem Zeitplan zugeordnet.
Ich habe den Raum gebucht, dabei aber absichtlich den Zeitplan missachtet und die Schließungszeit am Abend ignoriert. Dann erhalte ich die Fehlermeldung "Testraum darf nur innerhalb der im Zeitplan angegebenen Zeitfenster gebucht werden" mit der Aufforderung einen freien Zeitslot auszuwählen. Nur kann ich den leider nicht auswählen, weil das loading Ding in die Unendlichkeit lädt:
![Bildschirmfoto_6-3-2024_8577_mzcrew simren de](https://github.com/tiloman/simren-issues/assets/129038745/14930a67-70c1-4047-979c-8ed4558a5ccf)

**Comment by tiloman** [comment]
Kalender wurde geupdated. Auswahl auserhalb der Öffnungszeiten nicht mehr möglich. Damit gefixt
