### ISSUE TITLE
Thekenlösung

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#94]
Bei uns in der UB werden Geräte vom Medienzentrum ausgegeben, die Rückgabe der Geräte kann aber während der gesamten Öffnungszeiten (8-24 Uhr) an der Haupttheke erfolgen. Hierfür wäre es schön, wenn die Theken-Kolleg_innen eine spezielle Thekenlösung hätten, die sehr reduziert ist und es ihnen nur ermöglicht, Geräte zurückzunehmen (was anderes machen die nicht!).

**Comment by tiloman** [comment]
Ich führe gerne eine neue Rolle ein, mit der User dann Geräte zurücknehmen können.

**Comment by tiloman** [comment]
Eine Rolle für das zurücknehmen ist angelegt und kann in den Usereinstellungen hinzugefügt werden. User haben dann zusätzlich in der Buchungsübersicht auch Buchungen, die aktuell ausgeliehen oder überfällig sind von anderen Usern. Diese können sie dann zurücknehmen. Ebenso ist auf dem Dashboard für User mit dieser Rolle die Buchungstabelle sichtbar.
