### ISSUE TITLE
unklar: Preise mit Mehrtwertsteuer?

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#96]
Es ist für mich spontan unklar, ob die Preise unter https://simren.de/pricing/ die Mehrwertsteuer beinhalten oder nicht. Muss nicht eigentlich immer der Zusatz „inkl. MwSt.” bei Preisen stehen...?

**Comment by tiloman** [comment]
Die Preise verstehen sich als Gesamtpreis. Da als Kleinunternehmen abgerechnet wird, entfällt die MWst.
