### ISSUE TITLE
Beschreibung Premium-Plan fehlerhaft

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#97]
Unter https://simren.de/pricing/ ist die Beschreibung des Premium-Plans fehlerhaft.
Dort heißt es: 

"für bis zu 200 Buchungen im Monat

    Nach 200 Buchungen wird der Premium Plan aktiviert. Alternativ können nach 20 Buchungen alle Buchungen für den Rest des Monats gestoppt werden."

Korrekt wäre:
""für bis zu 200 Buchungen im Monat

    Nach 200 Buchungen wird der Unlimited Plan aktiviert. Alternativ können nach 200 Buchungen alle Buchungen für den Rest des Monats gestoppt werden."

-> Unlimited & 200 (statt Premium und 20)

**Comment by tiloman** [comment]
Danke, ist korrigiert.
