### ISSUE TITLE
case sensitivity in der Suchfunktion

### ISSUE THREAD

**Issue by ccupb** [tiloman/simren-issues#98]
Die Suchfunktion erlaubt scheinbar nur kleingeschriebene Wörter. Wir haben z.B. "Audio-Aufnahmegeräte" im Inventar. Diese erscheinen aber über die Suche nur wenn man "audio" eingibt. Bei der Eingabe "Audio" wird nichts gefunden.

**Comment by tiloman** [comment]
Danke, ist gefixt (in ca. 30min)
