### ISSUE TITLE
Keine Übersicht von Rollen möglich

### ISSUE THREAD

**Issue by mimosel** [tiloman/simren-issues#99]
Im Administrationsbereich kann man zwar Gruppen einsehen, aber keine Rollen. Dass es das Konzept der Rolle gibt, wird eigentlich nur deutlich, wenn man Benutzer editiert. 
Wäre es nicht praktisch, wenn 

1. Im Administrationsbereich auch noch eine Seite "Rollen" wäre, wo man alle Rollen mit Mitgliedern sieht?
2. Auch im Support-Center von Simren führt eine Suche nach "Rollen" nur zur Seite "Benutzergruppen anlegen" (https://simren.de/support/so-legst-du-benutzergruppen-an/ ), wo der Begriff "Benutzerrolle" zwar auftaucht, aber anscheinend "Benutzergruppe" meint.

Auch könnte man nochmal ganz allgemein überlegen, warum es überhaupt eine Unterscheidung zwischen Gruppen und Rollen gibt...

**Comment by tiloman** [comment]
Die simren seite zu aktualisieren steht noch auf der Agenda. Der Begriff ist dort falsch genutzt. Das werde ich korrigieren. 

Unterschied zwischen Gruppe und Rolle ist für mich recht eindeutig: 
- Rolle: Einzelne User können Sonderrechte bekommen.
- Gruppe: Eine gruppe von Usern (Studierende, Mitarbeitende, Kursteilnehmende) bekommt die Möglichkeit spezielle Ressourcen zu verleihen oder auch zu administrieren. 

Man könnte theoretisch natürlich auch noch Rollen mit Gruppen verknüpfen, sodass User einer bestimmten Gruppe automatisch auch eine Rolle bekommen..

**Comment by tiloman** [comment]
Habe eine Filtermöglichkeit für Rollen hinzugefügt in der Userübersicht.
